/**
 * Pipeline Output Types — Generated by AI agents.
 * These represent the analytical layer: scores, assessments,
 * recommendations, and plans produced by the 5-agent pipeline.
 */

// --- Role Forecasting Agent ---
export interface PipelineRoleForecast {
  prioritized_roles: PipelineForecastedRole[];
  analysis_summary?: string;
}

export interface PipelineForecastedRole {
  role_id: string;
  title: string;
  department_id?: string;
  urgency_score: number;
  strategic_importance: string;
  opening_in_months: number;
  key_requirements_summary: string[];
  risk_if_unfilled?: string;
}

// --- Employee Trajectory Agent ---
export interface PipelineEmployeeTrajectories {
  employee_trajectories: PipelineEmployeeTrajectory[];
}

export interface PipelineEmployeeTrajectory {
  employee_id: string;
  name: string;
  current_role: string;
  department_id?: string;
  trajectory_score: number;
  readiness_horizon_months: number;
  growth_velocity: "high" | "medium" | "low";
  key_strengths: string[];
  critical_gaps: string[];
  trajectory_summary?: string;
}

// --- Gap Bridging / Role Matching Agent ---
export interface PipelineRoleMatches {
  role_matches: PipelineRoleMatch[];
  overall_pipeline_health: string;
  pipeline_summary?: string;
}

export interface PipelineRoleMatch {
  role_id: string;
  role_title: string;
  department_id?: string;
  recommendation: "internal" | "external" | "hybrid";
  top_candidates: PipelineCandidate[];
  external_hire_needed: boolean;
  external_hire_reasoning?: string;
  urgency_score?: number;
}

export interface PipelineCandidate {
  employee_id: string;
  name: string;
  fit_score: number;
  will_be_ready_in_months: number;
  match_reasoning?: string;
  gaps_to_close: string[];
}

// --- Development Planning Agent ---
export interface PipelineDevelopmentPlans {
  development_plans: PipelineDevelopmentPlan[];
}

export interface PipelineDevelopmentPlan {
  employee_id: string;
  employee_name: string;
  target_role_id: string;
  target_role_title: string;
  timeline_months: number;
  interventions: PipelineIntervention[];
  success_metrics: string[];
  risk_if_not_done: string;
}

export interface PipelineIntervention {
  type: string;
  title: string;
  description?: string;
  duration_months: number;
  gap_addressed: string;
  priority: string;
}

// --- Decision Synthesis Agent ---
export interface PipelineFinalDecision {
  executive_summary: string;
  pipeline_health: string;
  decisions: PipelineDecision[];
  top_hidden_talent: PipelineHiddenTalent[];
  org_risks: string[];
}

export interface PipelineDecision {
  role_id: string;
  role_title: string;
  department_id?: string;
  recommended_action?: string;
  action_type: string;
  primary_candidate?: string;
  urgency: string;
  confidence: string;
  key_risk: string;
  next_step: string;
}

export interface PipelineHiddenTalent {
  employee_id: string;
  name: string;
  insight: string;
}

// --- Full pipeline response ---
export interface PipelineAgents {
  role_forecast: PipelineRoleForecast;
  employee_trajectories: PipelineEmployeeTrajectories;
  role_matches: PipelineRoleMatches;
  development_plans: PipelineDevelopmentPlans;
  final_decision: PipelineFinalDecision;
}

export interface PipelineResponse {
  success: boolean;
  data: {
    agents: PipelineAgents;
  };
}
